# Stacksize Configuration
# Reference: https://github.com/Torm/Stacksize/blob/master/README.md
# Updates to this file while the plugin is running will be detected and the configuration will be reloaded.



# Version of the configuration. Do not change.
version: 2

# Plugin is required to work. The server is shut down otherwise.
required: false

# A selection of events that will be logged.
# STACK_SIZE_MODIFIED: Log when a material's maximum stack size is modified.
# CONFIGURATION_MODIFIED: Log when the configuration is modified or is loaded/reloaded.
log:
  - STACK_SIZE_MODIFIED
  - CONFIGURATION_MODIFIED

# The maximum stack sizes of materials.
# See a list of materials: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html.
# Materials that are not items (which cannot be stored in an inventory) are ignored.
stackSizes:

  # Balance the amount of processed food that can be carried in one inventory slot.
  BREAD: 64
  COOKED_BEEF: 64
  COOKED_PORKCHOP: 64
  BAKED_POTATO: 64
  COOKED_CHICKEN: 64
  COOKED_COD: 64
  COOKED_MUTTON: 64
  COOKED_RABBIT: 64
  COOKED_SALMON: 64
  PUMPKIN_PIE: 64
  ENCHANTED_GOLDEN_APPLE: 64
  GOLDEN_APPLE: 64
  GOLDEN_CARROT: 64
  APPLE: 64

  # Make potions more useful by allowing multiple in one inventory slot.
  POTION: 4
  SPLASH_POTION: 8
  LINGERING_POTION: 8

  # Make boats and minecarts easier to carry around by raising their stack sizes from 1 to 4.
  OAK_BOAT: 4
  ACACIA_BOAT: 4
  SPRUCE_BOAT: 4
  JUNGLE_BOAT: 4
  BIRCH_BOAT: 4
  DARK_OAK_BOAT: 4

  MINECART: 4
  CHEST_MINECART: 4
  HOPPER_MINECART: 4
  FURNACE_MINECART: 4
  TNT_MINECART: 4
  COMMAND_BLOCK_MINECART: 4

  SADDLE: 64
